# Example experiment file

global:
  seed: 2025
  device: cpu # 'cpu' or 'cuda'
  results_dir: results/demo # results

# data
# - tag : single OpenML tag (e.g. openml__iris__59)
# - group : name in configs/datasets.yaml (e.g. cls56)
dataset:
  tag: openml__iris__59
  # group: cls56

# feature transforms
# name: Identity -> no transform
feature_preprocessing:
  # name: Identity
  numeric:
    - yeo_johnson
  categorical:
    - one_hot

# SVDTrainer
train:
  num_epochs: 20
  batch_size: 512
  lr: 1e-3

# Context (one or several - give a list)
context:
  name: scarf
  parameters:
    num_contexts: 2
    distribution: uniform
    corruption_rate: 0.2

# Encoder (same MLP for x and a)
encoder:
  name: MLPEncoder
  parameters:
    hidden_dims: [128, 128]
    output_dim: 64

# Encoder (separate x/a encoders)
# encoder:
#   x:
#     name: MLPEncoder
#     parameters:
#       hidden_dims: [64, 64]
#       output_dim: 64
#   a:
#     name: MLPEncoder
#     parameters:
#       hidden_dims: [128, 64, 128]
#       output_dim: 64

# Loss for SVDTrainer
losses:
  name: EVDLoRA
  parameters:
    exp_parameterization: inner_product
    temperature: 1.0

# Frozen linear probe
probe:
  max_epochs: 100
  batch_size: 256
  early_stopping_patience: 10
  lr: 0.02
  weight_decay: 1e-4
